version: "3.9"

services:
  mysql:
    image: mysql
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin_password
      MYSQL_DATABASE: appliance_manager
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
